title: "Aewoo's Translation"
description: "English translations of Chinese historical fiction."
theme: minima
markdown: kramdown
sass:
  style: compressed
collections:
  novel-one:
    output: true
    sort_by: order
    permalink: /DILOANH/:path/
  novel-two:
    output: true
    sort_by: order
    permalink: /TDHIDIL/:path/
