title: "Aewoo's Translation"
description: "English translations of Chinese historical fiction."
theme: minima
markdown: kramdown
sass:
  style: compressed
collections:
  novel_one:
    output: true
  novel_two:
    output: true
