title: "Aewoo's Translation"
description: "English translations of Chinese historical fiction."
theme: minima
markdown: kramdown
sass:
  style: compressed
collections:
  novel-one:
    output: true
    permalink: /novel-one/:name/
  novel-two:
    output: true
    permalink: /novel-two/:name/
